highlighter: rouge
permalink: ./:title
title: "Weak Notes"
description: "A public second brain"
author: "Mat"
url: https://thechels.uk
copyright: "MB"
encoding: UTF-8
future: false
repository: Mat-0/TheChels.uk
defaultImagePath: "/images/splashscreens/apple-touch-icon-180x180.png"
github:
  repository_url: https://github.com/Mat-0/TheChels.uk
  branch: main
sass:
  style: compressed
plugins:
  - jekyll-feed
  - jekyll-avatar
  - jekyll-github-metadata
exclude:
  - CNAME
  - README.md
  - LICENSE.md
  - SECURITY.md
  - requirements.txt
  - _python/
  - .github/
include:
  - ".well-known"
  - "_pages"

# Site Navigation
## Header
navigation_header:
  - link: "https://thechels.uk/about"
    title: "About"
  - link: "https://thechels.uk/cv"
    title: "CV"
  - link: "https://thechels.uk/daily"
    title: "Daily"
  - link: "https://thechels.uk/offers"
    title: "Offers"
  - link: "https://decodingyourmanager.substack.com/"
    title: "SubStack &raquo;"
  - link: "https://shop.the-ensemblist.uk"
    title: "Shop &raquo;"
## SubMenu
navigation_subpages:
  - link: "/about"
    title: "Bio"
  - link: "/manual"
    title: "Manual"
  - link: "/podcasts"
    title: "Podcasts"
  - link: "/teams"
    title: "Football Teams"
  - link: "/books"
    title: "Books"
  - link: "/gear"
    title: "Use"

## Footer links
navigation_footer:
  - link: "https://thechels.uk/feed.json"
    title: "RSS"
  - link: "https://thechels.uk/sitemap.xml"
    title: "Sitemap"
  - link: "https://thechels.uk/humans.txt"
    title: "Humans"
  - link: "https://thechels.uk/robots.txt"
    title: "Robots"
  - link: "https://thechels.uk/.well-known/privacy.txt"
    title: "Privacy"
  - link: "https://thechels.uk/.well-known/security.txt"
    title: "Security"
  - link: "https://www.linkedin.com/in/mat-benfield/"
    title: "LinkedIn &raquo;"
  - link: "https://github.com/Mat-0/"
    title: "GitHub &raquo;"
