name: Add a Book 5
run-name: üìö ${{ inputs['book-status'] }} book ${{ inputs.identifier }}

# Grant the action permission to write to the repository
permissions:
    contents: write
    pull-requests: write

# Trigger the action
on:
    workflow_dispatch:
        inputs:
            book-status:
                description: What is the status of the book? Required.
                required: true
                default: "finished"
            date:
                description: Date to record the status of the book (YYYY-MM-DD). Leave blank for today. Optional.
                type: string
            identifier:
                description: The book's identifier. This is an ISBN, Libby or Libro.fm share URL. Required.
                # Example values: 9780062315007
                required: true
                type: string

# Set up the steps to run the action
jobs:
    update-library:
        runs-on: ubuntu-latest
        name: Read
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Read
              id: read_action
              with:
                  set-image: true
              uses: library-pals/read-action@v9.5.0

            - name: Download the book thumbnail
              if: env.BookThumbOutput != ''
              run: curl "${{ env.BookThumb }}" -o "img/${{ env.BookThumbOutput }}"

            - name: Commit updated read file
              if: env.BookNeedsReview != 'true' # Do not commit book if it needs review
              run: |
                  git pull
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git add -A && git commit -m "üìö ‚Äú${{ env.BookTitle }}‚Äù (${{ env.BookStatus }})"
                  git push

            # Add this step to your workflow if you want the ability to fix the missing data by making the action open a new pull request.
            - name: If book needs review, create a pull request to review book metadata
              if: env.BookNeedsReview == 'true'
              run: |
                  git config pull.rebase true
                  git fetch origin
                  git config --local user.email "action@github.com"
                  git config --local user.name "GitHub Action"
                  git checkout -b review-book-${{env.BookIsbn}}
                  git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
                  git add -A && git commit -m "üìö ‚Äú${{ env.BookTitle }}‚Äù (${{ env.BookStatus }})" -m "‚Äú${{ env.BookTitle }}‚Äù is missing the following properties: ${{env.BookMissingMetadata}}. Edit this pull request to add them or merge it in."
                  git push --set-upstream origin review-book-${{env.BookIsbn}}
                  gh pr create -B main -H "review-book-${{env.BookIsbn}}" --fill
              env:
                  GH_TOKEN: ${{ github.token }}
